Rscript   filterChromXY.R     1_All-Chromosomes     10_W1733C-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     10_W1733D-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     10_W1733F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     10_W1733M-Mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     11_W1398C-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     11_W1398D-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     11_W1398F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     11_W1398M-mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     12_Q17-W1579D-boy-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     12_Q18-W1579F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     12_Q19-W1579M-mother-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     12_W1579C-boy-ICSI-fresh-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     13_Q23-W1647M-mother-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     13_W1647C-boy-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     13_W1647D-boy-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     13_W1647F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     14_Q15-W1719M-mother-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     14_W1719C-boy-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     14_W1719D-boy-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     14_W1719F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     15_Q10-W871M-mother-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     15_Q4-W871D-boy-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     15_Q6-W871C-boy-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     15_Q7-W871F-father-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     16_W839C-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     16_W839D-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     16_W839F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     16_W839M-Mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     17_Q21-W1524M-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     17_Q24-W1524C-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     17_W1524D-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     17_W1524F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     18_W1387C-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     18_W1387D-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     18_W1387F-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     18_W1387M-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     19_W1458C-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     19_W1458D-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     19_W1458F-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     19_W1458M-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     1_A42C-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     1_A42D-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     1_A42F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     1_A42M-Mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     20_W1191C-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     20_W1191D-ICSI-fresh-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     20_W1191F-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     20_W1191M-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     21_Q20-W1507F-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     21_W1507C-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     21_W1507D-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     21_W1507M-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     22_W1636C-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     22_W1636D-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     22_W1636F-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     22_W1636M-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     23_E45C-girl-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     23_E45D-boy-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     23_E45F-father-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     23_E45M-Mother-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     24_W774C-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     24_W774D-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     24_W774F-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     24_W774M-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     25_E115C-boy-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     25_E115D-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     25_E115F-father-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     25_E115M-mother-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     26_A19C-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     26_A19D-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     26_A19F-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     26_A19M-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     27_E16C-boy-NC-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     27_E16F-father-NC_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     27_E16M-mother-NC-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     28_E23C-boy-IVF-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     28_E23-IVF-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     28_E23-IVF-fresh-M-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     29_W76C-boy-IVF-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     29_W76-IVF-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     29_W76-IVF-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     2_Q16-W1785M-mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     2_W1785C-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     2_W1785D-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     2_W1785F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     30_Q22-W1452C-boy-IVF-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     30_W1452-IVF-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     30_W1452-IVF-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     31_W1149C-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     31_W1149-IVF-frozen-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     31_W1149-IVF-frozen-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     32_W88C-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     32_W88-IVF-frozen-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     32_W88-IVF-frozen-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     33_W104C-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     33_W104-IVF-frozen-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     33_W104-IVF-frozen-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     34_W200C-boy-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     34_W200-ICSI-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     34_W200-ICSI-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     35_W766C-boy-ICSI-fresh-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     35_W766F-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     35_W766M-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     36_W928C-boy-ICSI-fresh-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     36_W928-ICSI-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     36_W928-ICSI-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     37_W618C-boy-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     37_W618-ICSI-frozen-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     37_W618-ICSI-frozen-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     38_W1531C-boy-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     38_W1531-ICSI-frozen-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     38_W1531-ICSI-frozen-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     39_W1656F-father-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     39_W1656-ICSI-frozen-C_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     39_W1656M-mother-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     3_Q2-W811M-mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     3_Q8-W811F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     3_Q9-W811C-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     3_W811D-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     40_E12C-girl-NC_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     40_E12F-father-NC_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     40_E12M-mother-NC_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     41_E13C-girl-NC_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     41_E13F-father-NC_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     41_E13M-mother-NC_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     42_W53C-girl-IVF-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     42_W53-IVF-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     42_W53-IVF-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     43_W81C-girl-IVF-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     43_W81-IVF-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     43_W81-IVF-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     44_W1694F-father-IVF-fresh-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     44_W1694-IVF-fresh-C_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     44_W1694M-mother-IVF-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     45_E14C-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     45_E14F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     45_E14M-mother-IVF-frozen-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     46_W857C-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     46_W857F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     46_W857M-mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     47_E32C-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     47_E32F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     47_E32M-mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     48_W808C-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     48_W808F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     48_W808M-mother-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     49_W924C-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     49_W924-ICSI-fresh-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     49_W924-ICSI-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     4_W28C-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     4_W28D-girl-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     4_W28F-father-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     4_W28M-Mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     50_W934C-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     50_W934F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     50_W934-ICSI-fresh-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     51_W1699C-girl-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     51_W1699F-father-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     51_W1699M-mother-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     52_W39-ICSI-frozen-C_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     52_W39-ICSI-frozen-F_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     52_W39-ICSI-frozen-M_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     5_E95C-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     5_E95D-girl-ICSI-fresh-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     5_E95F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     5_E95M-Mother-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     61_NC-BS2-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     61_NC-BS2-D-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     61_NC-BS2-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     61_NC-BS2-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_BS20D-NC-girl_Rep4.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_NC-BS20-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_NC-BS20-C-Girl_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_NC-BS20-D-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_NC-BS20-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_NC-BS20-F-Father_Rep5.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_NC-BS20-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     62_NC-BS20-M-Mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     63_NC-E8-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     63_NC-E8-C-Girl_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     63_NC-E8-D-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     63_NC-E8-D-Girl_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     63_NC-E8-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     63_NC-E8-F-Father_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     63_NC-E8-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     64_ART-BS18-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     64_ART-BS18-D-Girl_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     64_ART-BS18-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     64_ART-BS18-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-C-Girl_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-D-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-D-Girl_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     65_ART-BS29-M-Mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     66_ART-E29-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     66_ART-E29-C-Girl_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     66_ART-E29-D-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     66_ART-E29-D-Girl_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     66_ART-E29-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     66_ART-E29-F-Father_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     66_ART-E29-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     67_E24C-boy-NC_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     67_E24D-boy-NC_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     67_NC-E24-C-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     67_NC-E24-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     67_NC-E24-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     67_NC-E24-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     67_NC-E24-M-Mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_E56C-boy-NC_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_E56D-boy-NC_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_E56F-father-NC_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_E56M-mother-NC_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_NC-E56-C-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_NC-E56-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_NC-E56-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     68_NC-E56-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     69_NC-E123-C-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     69_NC-E123-C-Boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     69_NC-E123-D-Boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     69_NC-E123-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     69_NC-E123-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     69_NC-E123-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     6_W655C-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     6_W655D-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     6_W655F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     6_W655M-Mother-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_ART-E113-C-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_ART-E113-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_ART-E113-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_ART-E113-M-mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_E113C-boy-ART_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_E113D-boy-ART_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_E113F-father-ART_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     70_E113M-mother-ART_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     71_ART-W58-C-Boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     71_ART-W58-D-Boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     71_ART-W58-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     71_ART-W58-M-Mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     72_ART-W779-C-Boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     72_ART-W779-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     72_ART-W779-M-Mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     72_W779D-ART-boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     73_NC-E114-C-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     73_NC-E114-D-Girl_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     73_NC-E114-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     73_NC-E114-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_E54-NC-C_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_E54-NC-D_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_E54-NC-M_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_NC-E54-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_NC-E54-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_NC-E54-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_NC-E54-F-Father_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     74_NC-E54-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_E98-NC-C_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_E98-NC-D_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_E98-NC-F_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_E98-NC-M_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_NC-E98-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_NC-E98-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_NC-E98-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     75_NC-E98-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-C-Girl_Rep4.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-D-Boy_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-F-Father_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     76_ART-E18-M-Mother_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     77_ART-E69-C-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     77_ART-E69-D-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     77_ART-E69-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     77_ART-E69-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     77_ART-E69-M-Mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     77_E69-ART-C_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     77_E69-ART-D_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     78_ART-E101-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     78_ART-E101-C-Girl_Rep2.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     78_ART-E101-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     78_ART-E101-D-Boy_Rep4.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     78_ART-E101-F-Father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     78_ART-E101-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     78_ART-E101-M-Mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_ART-E72-C-Girl-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_ART-E72-D-Boy-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_ART-E72-F-Father-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_ART-E72-F-Father_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_ART-E72-M-Mother-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_E72-ART-C_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_E72-ART-D_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     79_E72-ART-M_Rep3.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     7_W1276C-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     7_W1276D-girl-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     7_W1276F-father-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     7_W1276M-mother-ICSI-fresh_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     8_W845C-girl-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     8_W845D-girl-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     8_W845F-father-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     8_W845M-Mother-ICSI-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     9_Q1-W1365M-mother-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     9_Q5-W1365D-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     9_W1365C-boy-IVF-frozen_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     9_W1365F-father-IVF-frozen-merge_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     batch1_1_A53C-boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     batch1_2_A53D-boy_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     batch1_3_A53F-father_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     batch1_4_A53M-mother_Rep1.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_101_E114C-boy-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_101_E114D-girl-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_101_E114F-father-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_101_E114M-mother-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_102_E54C-girl-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_102_E54D-boy-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_102_E54F-father-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_111_E18D-boy-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_111_E18F-father-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_113_E101C-girl-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_113_E101D-boy-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_113_E101F-father-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_113_E101M-mother-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_114_E72F-father-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_11_BS18C-girl-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_11_BS18D-girl-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_12_BS29C-girl-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_12_BS29D-girl-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_12_BS29F-father-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_13_E29M-mother-IVFfresh_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_1_BS2C-girl-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_1_BS2D-girl-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_1_BS2M-mother-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_3_E8C-girl-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_3_E8F-father-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_3_E8M-mother-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_51_E24M-mother-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_69_A53C-boy-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     chenwei_69_A53D-boy-NC_Rep9.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_10_E10C-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_10_E10D-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_10_E10M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_1_E1C-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_1_E1D-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_1_E1M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_2_E2C-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_2_E2D-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_2_E2M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_3_E3C-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_3_E3D-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_3_E3M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_4_E4C-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_4_E4D-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_4_E4M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_5_E5C-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_5_E5D-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_5_E5M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_6_E6C-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_6_E6M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_7_E7C-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_7_E7D-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_8_E8C-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_8_E8M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_9_E9C-girl_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_9_E9D-boy_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     EM_9_E9M-mother_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_1000_M28-A53C_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_1000_M29-A53D_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_10_P10C-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_10_P10D-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_10_P10M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_1_P1C-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_1_P1D-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_1_P1M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_2_P2C-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_2_P2D-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_2_P2M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_3_P3C-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_3_P3D-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_3_P3M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_4_P4C-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_4_P4D-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_4_P4M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_5_P5C-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_5_P5D-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_5_P5M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_6_P6C-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_6_P6D-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_6_P6M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_7_P7C-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_7_P7D-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_7_P7M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_8_P8C-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_8_P8D-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_8_P8M-mother-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_9_P9C-girl-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_9_P9D-boy-PCOS_Rep1.CpG.bismark.cov
Rscript   filterChromXY.R     1_All-Chromosomes     PCOS_9_P9M-mother-PCOS_Rep1.CpG.bismark.cov
